jobs:
    cue_export_dev:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          run: cue export -e deployment_dev -e service_dev  use-cases/k8s/export/nginx.cue --out yaml
    cue_export_tst:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          run: cue export -e deployment_tst -e service_tst  use-cases/k8s/export/nginx.cue --out yaml
    cue_export_prd:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          run: cue export -e deployment_prd -e service_prd  use-cases/k8s/export/nginx.cue --out yaml
           
    cue_eval_ok:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          run: cue eval use-cases/k8s/eval/schema.cue
    cue_eval_fail:
      runs-on: ubuntu-latest
      continue-on-error: true
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          run: cue eval use-cases/k8s/eval/schema.fail.cue
    cue_vet_ok:
      runs-on: ubuntu-latest
      continue-on-error: true
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          working-directory: use-cases/k8s/vet/
          run: cue vet nginx.yaml schema.cue -d "#Schema"
    cue_vet_fail_int:
      runs-on: ubuntu-latest
      continue-on-error: true
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          working-directory: use-cases/k8s/vet/
          run: cue vet nginx-fail-int.yaml schema.cue -d "#Schema"
    cue_vet_fail_typo:
      runs-on: ubuntu-latest
      continue-on-error: true
      defaults:
        run:
          shell: bash
      steps:
        - name: Install CUE
          uses: cue-lang/setup-cue@v1.0.0-alpha.2
          with:
            version: v0.4.1-beta.6
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate K8S YAML from CUE
          working-directory: use-cases/k8s/vet/
          run: cue vet nginx-fail-typo.yaml schema.cue -d "#Schema"
"on":
  - push
name: Main Workflow